version: "3"
services:
  hamachi:
    image: mjenz/hamachi:2.1.0.203
    restart: unless-stopped
    volumes:
      - /var/lib/logmein-hamachi:/var/lib/logmein-hamachi:rw
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: "host"
